---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Docker installation
      become: true
      vars:
        gather_facts: true
        ansible_ssh_user: "{{ ansible_user }}"
        ansible_ssh_common_args: -o StrictHostKeyChecking=no
        package_names_docker:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          #- docker-compose-plugin
        dependencies_for_docker:
          - ca-certificates
          - curl
          - gnupg-agent
        docker_gpg: https://download.docker.com/linux/ubuntu/gpg
        apt_repository_docker: |
          deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        when_not_install: "{{package_names_docker| list }}"

      block:
        - name: Add universe
          apt_repository:
            repo: deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe
            state: present

        - name: Dependencies for docker
          ansible.builtin.apt:
            name: "{{ dependencies_for_docker }}"
            state: present
            update_cache: true

        - name: Add GPG
          apt_key:
            url: "{{ docker_gpg }}"
            state: present

        - name: Add repository docker
          apt_repository:
            repo: "{{ apt_repository_docker }}"
            state: present

        - name: Install a list of packages
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop: "{{ when_not_install }}"

        # - name: Install additional packages
        #   apt:
        #     name:
        #       - apt-transport-https
        #       - ca-certificates
        #       - curl
        #       - gnupg
        #       - lsb-release
        #     update-cache: true
        #     cache_valid_time: 86400

        # - name: Create Docker Key folder
        #   file:
        #     path: /etc/apt/keyrings
        #     state: directory
        #     mode: "0755"

        # - name: Add Docker Key
        #   apt_key:
        #     url: https://download.docker.com/linux/ubuntu/gpg
        #     keyring: /etc/apt/keyrings/docker.gpg
        #     state: present

        # - name: Install stable repositorie
        #   apt_repository:
        #     repo: deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        #     update-cache: true
        #     state: present
        #     filename: docker
        #   register: repositor

        # - debug:
        #     msg: "{{ansible_distribution}}"

        # - name: Install Docker-ce
        #   package:
        #     name: '{{ item }}'
        #     state: latest
        #     update-cache: true
        #   with_items:
        #   - docker-ce
        #   - docker-ce-cli

        - name: Docker is install and reboot
          service:
            name: docker
            state: restarted
            enabled: true

    - name: Docker-compose installation
      become: true

      block:
        - name: Get latest version docker-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Create Docker-compose folder
          file:
            path: /usr/local/bin/docker-compose
            state: directory
            mode: "0755"

        - name: Install docker-compose
          get_url:
            url: https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: "0755"
    - name: Finished step installation
      become: true

      block:
        - name: Add user in Docker Group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true

        - name: Reboot server
          reboot:
    - name: Create docker nginx image
      become: true
      block:
        - name: Copy conf and index file to remote machine
          ansible.builtin.copy:
            src: ngnx/
            dest: ngnx_files
            mode: "0755"
            force: true

        - name: Build Nginx image
          community.docker.docker_container:
            name: nginx
            image: nginx
            state: started
            volumes:
              - ~/ngnx_files/ngnx.conf:/etc/nginx/conf.d/default.conf
              - /home/vagrant/ngnx_files/index.html:/usr/share/nginx/html/index.html
            ports:
              - 8081:80
